services:
  chatbot_backend:
    environment:
      - USE_GPU=true # set env variable to true so that code can apply specific GPU configuration to text encoder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-llm:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]