from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from src.query_handler.QueryHandler import query_handler
from src.db_manager.ChatHistoryManager import chat_history_manager
from src.rag.MWPClient import MWPClient
from src.rag.ChunkSelector import ChunkSelector
from src.rag.ContextGenerator import ContextGenerator
from src.rag.TextEmbedder import TextEmbedder

app = FastAPI()


class ChatInput(BaseModel):
    """Input model for chat endpoint.

    Attributes:
        session_id: Unique identifier for the chat session.
        query: User's input query.
    """
    session_id: str
    query: str


class ChatOutput(BaseModel):
    """Output model for chat endpoint.

    Attributes:
        info: Information about the query processing.
        query_answer: Answer generated by the LLM.
        standalone_query: Rewritten query for clarity.
        relevant_urls: List of URLs relevant to the query.
        extracted_content: Preview of extracted content from relevant_urls.
        reference_urls: Set of URLs used as references. Subset of relevant_urls, retrieved from URLs of relevant_chunks.
        relevant_chunks: List of relevant text chunks extracted.
        status: Status of the query processing.
    """
    info: str
    query_answer: str = ""
    standalone_query: str = ""
    selected_domain: str = ""
    relevant_urls: list[str] = []
    extracted_content: list[dict] = []
    reference_urls: set[str] = set()
    relevant_chunks: list[str] = []
    status: str = "success"


@app.post("/chat")
def chat(message: ChatInput) -> ChatOutput:
    """Processes a user's chat query and returns a response.
    
    Checks if the query is valid, retrieves relevant URLs, extracts content, selects useful chunks 
    and generates an answer with extracted chunks as context.

    Args:
        message: Input containing session_id and query.

    Returns:
        ChatOutput: Response containing query processing details and answer.
    """
    intent_result = query_handler.process_query(message.session_id, message.query)

    if not intent_result.is_allowed:
        rejection_msg = "Your query appears to be meaningless or invalid. Please ask a clear, answerable question."

        chat_history_manager.add_message(message.session_id, "user", message.query)
        chat_history_manager.add_message(message.session_id, "assistant", rejection_msg)
        return ChatOutput(
            info=rejection_msg,
            standalone_query=intent_result.standalone_query,
            status="rejected",
        )

    extracted_contents: list[dict[str, str]] = []

    parsed_content: list[tuple[str, str]] = []  # a list of tuples containing pairs <url, parsed_text>

    for url in intent_result.relevant_urls:
        if MWPClient.is_domain_supported(url):
            parsed_text = MWPClient.parse_url(url)
            if parsed_text:
                parsed_content.append((url, parsed_text))
                extracted_contents.append(
                    {
                        "url": url,
                        "content_preview": parsed_text[:300]
                        + "...",  # return a preview for testing
                    }
                )

    urls_found = len(intent_result.relevant_urls)
    parsed_count = len(extracted_contents)

    rag_data: dict[str, list[str]] = ChunkSelector.select_relevant_chunks(
        query=intent_result.standalone_query, parsed_pages=parsed_content
    )
    relevant_chunks: list[str] = []

    for chunks in rag_data.values():
        relevant_chunks.extend(chunks)

    reference_urls: set[str] = set(rag_data.keys())

    # we will later pass this to LLM
    query_context_data: str = ContextGenerator.generate_llm_context(
        extracted_chunks=relevant_chunks
    )

    llm_answer: str = query_handler.answer_query(message.session_id, intent_result.standalone_query, query_context_data)

    success_msg = f"Query accepted! Rewritten as: '{intent_result.standalone_query}'. Found {urls_found} URLs, parsed {parsed_count} via MWP."

    chat_history_manager.add_message(message.session_id, "user", message.query)
    chat_history_manager.add_message(message.session_id, "assistant", success_msg)

    return ChatOutput(
        info=success_msg,
        query_answer=llm_answer,
        standalone_query=intent_result.standalone_query,
        selected_domain=intent_result.selected_domain,
        relevant_urls=intent_result.relevant_urls,
        extracted_content=extracted_contents,
        reference_urls=reference_urls,
        relevant_chunks=relevant_chunks,
        status="allowed",
    )


# to know if the server is alive or dead
@app.get("/health")
def health():

    """Checks the health status of the server.

    Returns:
        dict: A dictionary indicating the server's health status.
    """
    return {"status": "healthy"}

