from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from src.query_handler.QueryHandler import query_handler
from src.db_manager.ChatHistoryManager import chat_history_manager
from src.rag.MWPClient import MWPClient
from src.rag.ChunkSelector import ChunkSelector
from src.rag.ContextGenerator import ContextGenerator
from src.rag.TextEmbedder import TextEmbedder

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatInput(BaseModel):
    """Input model for chat endpoint.

    Attributes:
        session_id: Unique identifier for the chat session.
        query: User's input query.
    """
    session_id: str
    query: str


class ChatOutput(BaseModel):
    """Output model for chat endpoint.

    Attributes:
        info: Information about the query processing.
        query_answer: Answer generated by the LLM.
        standalone_query: Rewritten query for clarity.
        relevant_urls: List of URLs relevant to the query.
        extracted_content: Preview of extracted content from relevant_urls.
        reference_urls: Set of URLs used as references. Subset of relevant_urls, retrieved from URLs of relevant_chunks.
        relevant_chunks: List of relevant text chunks extracted.
        status: Status of the query processing.
    """
    info: str
    query_answer: str = ""
    standalone_query: str = ""
    selected_domain: str = ""
    relevant_urls: list[str] = []
    extracted_content: list[dict] = []
    reference_urls: set[str] = set()
    relevant_chunks: list[str] = []
    status: str = "success"


class CreateSessionInput(BaseModel):
    """Input for creating a new session."""
    title: str = "New Chat"


from fastapi.responses import StreamingResponse
import json

@app.post("/chat")
def chat(message: ChatInput):
    """Processes a user's chat query and streams the response via SSE.
    
    Checks if the query is valid, retrieves relevant URLs, extracts content, selects useful chunks 
    and generates an answer with extracted chunks as context.

    Args:
        message: Input containing session_id and query.

    Returns:
        StreamingResponse: SSE stream containing query processing details and answer tokens.
    """
    def event_stream():
        try:
            yield f"data: {json.dumps({'phase': 'status', 'content': 'Checking guardrails and intent...'})}\n\n"
            intent_result = query_handler.process_query(message.session_id, message.query)

            if not intent_result.is_allowed:
                rejection_msg = "Your query appears to be meaningless or invalid. Please ask a clear, answerable question."
                chat_history_manager.add_message(message.session_id, "user", message.query)
                chat_history_manager.add_message(message.session_id, "assistant", rejection_msg)
                yield f"data: {json.dumps({'phase': 'complete', 'content': rejection_msg, 'status': 'rejected'})}\n\n"
                return

            yield f"data: {json.dumps({'phase': 'status', 'content': f'Searching... Found {len(intent_result.relevant_urls)} sources.'})}\n\n"
            
            extracted_contents = []
            parsed_content = []
            
            for url in intent_result.relevant_urls:
                if MWPClient.is_domain_supported(url):
                    yield f"data: {json.dumps({'phase': 'status', 'content': f'Reading websites...'})}\n\n"
                    parsed_text = MWPClient.parse_url(url)
                    if parsed_text:
                        parsed_content.append((url, parsed_text))
                        extracted_contents.append({"url": url, "content_preview": parsed_text[:300] + "..."})

            yield f"data: {json.dumps({'phase': 'status', 'content': 'Reading and selecting relevant chunks...'})}\n\n"
            rag_data = ChunkSelector.select_relevant_chunks(
                query=intent_result.standalone_query, parsed_pages=parsed_content
            )
            relevant_chunks = []
            for chunks in rag_data.values():
                relevant_chunks.extend(chunks)
            
            query_context_data = ContextGenerator.generate_llm_context(extracted_chunks=relevant_chunks)
            
            yield f"data: {json.dumps({'phase': 'status', 'content': 'Generating answer...'})}\n\n"
            
            full_answer = ""
            for token in query_handler.stream_answer_query(message.session_id, intent_result.standalone_query, query_context_data):
                full_answer += token
                yield f"data: {json.dumps({'phase': 'token', 'content': token})}\n\n"

            chat_history_manager.add_message(message.session_id, "user", message.query)
            chat_history_manager.add_message(message.session_id, "assistant", full_answer)

            yield f"data: {json.dumps({'phase': 'complete', 'content': '', 'status': 'success'})}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'phase': 'error', 'content': str(e)})}\n\n"
            
    return StreamingResponse(event_stream(), media_type="text/event-stream")

@app.get("/sessions")
def list_sessions():
    """List all chat sessions."""
    return chat_history_manager.get_all_sessions()


@app.post("/sessions")
def create_session(body: CreateSessionInput = None):
    """Create a new chat session."""
    if body is None:
        body = CreateSessionInput()
    session_id = chat_history_manager.create_session(title=body.title)
    return {"session_id": session_id, "title": body.title}


@app.get("/sessions/{session_id}/messages")
def get_session_messages(session_id: str):
    """Get all messages for a session."""
    if not chat_history_manager.session_exists(session_id):
        raise HTTPException(status_code=404, detail="Session not found")
    return chat_history_manager.get_history(session_id)


@app.delete("/sessions/{session_id}")
def delete_session(session_id: str):
    """Delete a session and all its messages."""
    deleted = chat_history_manager.delete_session(session_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Session not found")
    return {"status": "deleted"}

@app.get("/health")
def health():
    """Checks the health status of the server.

    Returns:
        dict: A dictionary indicating the server's health status.
    """
    return {"status": "healthy"}