from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from src.query_handler.QueryHandler import query_handler
from src.db_manager.ChatHistoryManager import chat_history_manager
from src.rag.MWPClient import MWPClient
from src.rag.ChunkSelector import ChunkSelector
from src.rag.ContextGenerator import ContextGenerator

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatInput(BaseModel):
    """Input model for chat endpoint.

    Attributes:
        session_id: Unique identifier for the chat session.
        query: User's input query.
        always_search: Flag to force searching online instead of using cache.
    """
    session_id: str
    query: str
    always_search: bool = False # if set to True then use cached page parses stored in DB


class ChatOutput(BaseModel):
    """Output model for chat endpoint.

    Attributes:
        info: Information about the query processing.
        query_answer: Answer generated by the LLM.
        standalone_query: Rewritten query for clarity.
        relevant_urls: List of URLs relevant to the query.
        extracted_content: Preview of extracted content from relevant_urls.
        reference_urls: Set of URLs used as references. Subset of relevant_urls, retrieved from URLs of relevant_chunks.
        relevant_chunks: List of relevant text chunks extracted.
        status: Status of the query processing.
    """
    info: str
    query_answer: str = ""
    search_query: str = ""
    user_query: str = ""
    selected_domain: str = ""
    relevant_urls: list[str] = []
    extracted_content: list[dict] = []
    reference_urls: set[str] = set()
    relevant_chunks: list[str] = []
    status: str = "success"


class CreateSessionInput(BaseModel):
    """Input for creating a new session."""
    title: str = "New Chat"


from fastapi.responses import StreamingResponse
import json

@app.post("/chat")
def chat(message: ChatInput):
    """Processes a user's chat query and streams the response via SSE.
    
    Checks if the query is valid, retrieves relevant URLs, extracts content, selects useful chunks 
    and generates an answer with extracted chunks as context.

    Args:
        message: Input containing session_id and query.

    Returns:
        StreamingResponse: SSE stream containing query processing details and answer tokens.
    """
    def event_stream():
        try:
            yield f"data: {json.dumps({'phase': 'status', 'content': 'Checking guardrails and intent...'})}\n\n"
            intent_result = query_handler.process_query(message.session_id, message.query)

            if not intent_result.is_allowed or intent_result.is_ambiguous:
                rejection_msg = "Your query appears to be meaningless or invalid. Please ask a clear, answerable question." if (not intent_result.is_allowed and not intent_result.is_ambiguous) \
                                else (intent_result.requested_information) 
                chat_history_manager.add_message(message.session_id, "user", message.query)
                chat_history_manager.add_message(message.session_id, "assistant", rejection_msg)
                yield f"data: {json.dumps({'phase': 'complete', 'content': rejection_msg, 'status': 'rejected'})}\n\n"
                return

            yield f"data: {json.dumps({'phase': 'status', 'content': f'Searching... found {len(intent_result.relevant_urls)} sources.'})}\n\n"
            
            extracted_contents = []
            parsed_content = []
            
            for url in intent_result.relevant_urls:
                is_supported_domain: bool = MWPClient.is_domain_supported(url)
                yield f"data: {json.dumps({'phase': 'status', 'content': f'Extracting data from sources...'})}\n\n"
                parsed_text: str = ""
                cached_text: str | None = None 
                if (not message.always_search):
                    cached_text: str = chat_history_manager.get_parsed_text(url) # check for already parsed url to speed up llm answer
                if cached_text is None:
                    parsed_text = MWPClient.parse_url(url, generic_domain=(not is_supported_domain))
                    if (not message.always_search): # cache parsing in DB
                        chat_history_manager.save_parsed_text(url, parsed_text) 
                elif cached_text:
                    parsed_text = cached_text

                if parsed_text:
                    parsed_content.append((url, parsed_text))
                    extracted_contents.append({"url": url, "content_preview": parsed_text[:300] + "..."})

            yield f"data: {json.dumps({'phase': 'status', 'content': 'Assessing and selecting relevant information...'})}\n\n"
            rag_data = ChunkSelector.select_relevant_chunks(
                query=intent_result.search_query, parsed_pages=parsed_content
            )
            relevant_chunks = []
            for chunks in rag_data.values():
                relevant_chunks.extend(chunks)
            
            query_context_data = ContextGenerator.generate_llm_context(extracted_chunks=relevant_chunks)
            
            yield f"data: {json.dumps({'phase': 'status', 'content': 'Generating answer...'})}\n\n"
            
            full_answer = ""
            sources_data = ""
            sources_data = "\n\n**Fonti**:\n " + "\n".join(intent_result.relevant_urls)

            for token in query_handler.stream_answer_query(message.session_id, intent_result.user_query, query_context_data):
                full_answer += token
                yield f"data: {json.dumps({'phase': 'token', 'content': token})}\n\n"

            if not ("Mi dispiace," in full_answer or "I'm sorry," in full_answer):
                full_answer += sources_data
                yield f"data: {json.dumps({'phase': 'token', 'content': sources_data})}\n\n"

            chat_history_manager.add_message(message.session_id, "user", message.query)
            chat_history_manager.add_message(message.session_id, "assistant", full_answer)

            yield f"data: {json.dumps({'phase': 'complete', 'content': '', 'status': 'success'})}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'phase': 'error', 'content': str(e)})}\n\n"
            
    return StreamingResponse(event_stream(), media_type="text/event-stream")

@app.get("/sessions")
def list_sessions():
    """List all chat sessions."""
    return chat_history_manager.get_all_sessions()


@app.post("/sessions")
def create_session(body: CreateSessionInput = None):
    """Create a new chat session."""
    if body is None:
        body = CreateSessionInput()
    session_id = chat_history_manager.create_session(title=body.title)
    return {"session_id": session_id, "title": body.title}


@app.get("/sessions/{session_id}/messages")
def get_session_messages(session_id: str):
    """Get all messages for a session."""
    if not chat_history_manager.session_exists(session_id):
        raise HTTPException(status_code=404, detail="Session not found")
    return chat_history_manager.get_history(session_id)

# used for internal testing
@app.delete("/clear_cache")
def clear_cache() -> None:
    """Deletes all stored URL parsed texts from DB"""
    cleared = chat_history_manager.clear_all_url_cache()
    if not cleared:
        raise HTTPException(status_code=404, detail="Failed to clear parsed URLs cache")
    return {"status": "cleared"}

@app.delete("/sessions/{session_id}")
def delete_session(session_id: str):
    """Delete a session and all its messages."""
    deleted = chat_history_manager.delete_session(session_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Session not found")
    return {"status": "deleted"}

# to know if the server is alive or dead
@app.get("/health")
def health():
    """Checks the health status of the server.

    Returns:
        dict: A dictionary indicating the server's health status.
    """
    return {"status": "healthy"}