services:
  url_parser_backend:
    build:
      context: ./url_parser/backend
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./url_parser/backend:/app
      - ./url_parser/domains.json:/app/domains.json
      - ./url_parser/gs_data:/app/gs_data
    environment:
      - PYTHONUNBUFFERED=1

  url_parser_frontend:
    build:
      context: ./url_parser/frontend
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    volumes:
      - ./url_parser/frontend:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - url_parser_backend

  chatbot_backend:
    build:
      context: ./chatbot/backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001" # change if needed
    volumes:
      - ./chatbot/backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    #depends_on:
    #  - ollama

  chatbot_frontend:
    build:
      context: ./chatbot/frontend
      dockerfile: Dockerfile
    ports:
      - "8002:8002" # change if needed
    volumes:
      - ./chatbot/frontend:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - chatbot_backend


#   ollama:
#     image: ollama/ollama:latest
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama_data:/root/.ollama

#   ollama-pull-model:
#     image: ollama/ollama:latest
#     depends_on:
#       - ollama
#     environment:
#       - OLLAMA_HOST=ollama
#     entrypoint: /bin/sh
#     command: >
#       -c "
#       echo 'Waiting for Ollama to start...' &&
#       sleep 3 &&
#       echo 'Pre-loading model into memory...' &&
#       ollama run gemma2:2b \"\" &&
#       echo 'Model ready and loaded for API calls!'
#       "

# volumes:
#   ollama_data:
