use_default_settings:
  engines:
    keep_only:
          - google
          - bing
          - duckduckgo
          - wikipedia
          - qwant
server:
  base_url: http://localhost:8080/
  secret_key: "MINERVA_CHATBOT_SK_2sLmAZ#2!r%.0LmzaHYTox?" 

search:
  formats:
    - html
    - json 

outgoing:
  useragent_suffix: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"